In [1]:
pip install faiss-cpu

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
pip install sentence-transformers

     ---------------------------------------- 0.0/86.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/86.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/86.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/86.0 kB ? eta -:--:--
     ---- ----------------------------------- 10.2/86.0 kB ? eta -:--:--
     ---- ----------------------------------- 10.2/86.0 kB ? eta -:--:--
     ---- ----------------------------------- 10.2/86.0 kB ? eta -:--:--
     ---- ----------------------------------- 10.2/86.0 kB ? eta -:--:--
     ------------- ------------------------ 30.7/86.0 kB 119.1 kB/s eta 0:00:01
     ------------- ------------------------ 30.7/86.0 kB 119.1 kB/s eta 0:00:01
     ------------- ------------------------ 30.7/86.0 kB 119.1 kB/s eta 0:00:01
     ------------------ -------------------- 41.0/86.0 kB 93.4 kB/s eta 0:00:01
     ------------------ -------------------- 41.0/86.0 kB 93.4 kB/s eta 0:00:01
     ---------------


[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [4]:
df= pd.read_csv("D:\ML\Emotion_classify_Data.csv")

In [6]:
df.head()

Comment  \
0                            i seriously hate one subject to death but now i feel reluctant to drop it   
1                                                                   im so full of life i feel appalled   
2  i sit here to write i start to dig out my feelings and i think that i am afraid to accept the po...   
3            ive been really angry with r and i feel like an idiot for trusting him in the first place   
4              i feel suspicious if there is no one outside like the rapture has happened or something   

  Emotion  
0    fear  
1   anger  
2    fear  
3     joy  
4    fear

In [7]:
df.shape

(5937, 2)

In [11]:
from sentence_transformers import SentenceTransformer

In [13]:
encoder=SentenceTransformer("paraphrase-albert-small-v2")

In [16]:
# vectors=encoder.encode(df.Comment)
# encoder = YourEncoder()  # Replace YourEncoder() with the actual encoder you're using

# Assuming df is your DataFrame with a column named 'Comment'
comments_to_encode = df.head()['Comment']

# Encode the comments
vectors = encoder.encode(comments_to_encode)


In [17]:
vectors.shape

(5, 768)

In [27]:
vectors[0]

array([ 4.99080658e-01, -2.62388408e-01,  3.87139976e-01, -2.06825450e-01,
       -3.36135358e-01, -1.88161865e-01, -4.71417874e-01, -5.06358892e-02,
        1.76873629e-03,  4.16783601e-01, -4.29671288e-01,  2.07445025e-01,
       -5.48201263e-01,  6.99045122e-01,  1.77465439e-01,  1.46238089e-01,
        4.34413552e-01, -2.69811183e-01, -4.76339608e-01,  1.02947056e-01,
        3.00405324e-01, -1.88191175e-01,  2.00314522e-01, -2.80558914e-01,
       -8.68709803e-01,  5.81036091e-01,  3.77456307e-01,  3.13272744e-01,
       -1.39730200e-01, -1.47581428e-01, -4.23264802e-01, -3.72768864e-02,
        3.46389562e-01,  2.21188992e-01, -8.38730931e-02,  4.93044972e-01,
        1.15814233e+00, -2.41783336e-01, -5.60967438e-02, -1.18526630e-01,
       -3.61775100e-01, -5.88280797e-01,  2.33435765e-01,  2.02556103e-02,
        4.81150895e-01, -1.79625005e-02, -2.39118993e-01,  1.38019845e-01,
       -5.68894804e-01,  2.47598559e-01, -2.81574965e-01,  2.64341712e-01,
        1.95890591e-01,  

In [28]:
dim=vectors.shape[1]

In [29]:
dim

768

In [30]:
import faiss 

In [32]:
index=faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001A348884060> >

In [33]:
index.add(vectors)

In [46]:
search_query="I hate you"

vec=encoder.encode(search_query)
vec.shape

(768,)

In [47]:
vec

array([ 3.53170261e-02,  5.48580885e-02,  7.68975019e-02, -5.11862576e-01,
       -1.39677778e-01,  6.30597413e-01,  7.91516602e-02, -1.12155974e+00,
       -2.37402365e-01,  8.89715016e-01, -3.90968949e-01,  4.25162017e-01,
        5.38321614e-01,  6.04878604e-01, -7.78269649e-01,  8.30950379e-01,
        9.60473835e-01, -1.15746737e+00,  2.42732495e-01, -3.85694243e-02,
        4.03170675e-01,  4.83451903e-01,  9.16754127e-01, -2.68457025e-01,
        1.13725208e-01, -2.62614667e-01,  4.85730350e-01,  3.59603226e-01,
       -5.13193786e-01,  6.91885769e-01,  1.36675730e-01,  9.07011628e-01,
        4.15827602e-01,  4.64914814e-02, -6.03682399e-01,  1.84767753e-01,
        2.10674718e-01, -5.63321948e-01,  6.94019813e-03, -1.15271792e-01,
        3.88080209e-01, -6.83787346e-01,  2.39695787e-01,  5.07873595e-01,
        6.67056918e-01,  6.76938891e-01, -2.92935427e-02, -8.32455039e-01,
       -4.99787152e-01,  5.40522158e-01,  6.37131333e-01,  1.27024204e-01,
       -7.73612708e-02, -

In [48]:
import numpy as np
svec=np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [49]:
print(vec.shape)


(768,)


In [52]:
distance,I=index.search(svec,k=2)

In [53]:
I

array([[0, 2]], dtype=int64)

In [55]:
df.loc[I[0]]

Comment  \
0                            i seriously hate one subject to death but now i feel reluctant to drop it   
2  i sit here to write i start to dig out my feelings and i think that i am afraid to accept the po...   

  Emotion  
0    fear  
2    fear

In [56]:
search_query

'I hate you'

In [57]:
from langchain.embeddings import OpenAIEmbeddings

In [60]:
import vertexai
from vertexai.language_models import TextEmbeddingInput, TextEmbeddingModel

ModuleNotFoundError: No module named 'vertexai'

In [63]:
pip install vertexai


[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [64]:
import vertexai
from vertexai.language_models import TextEmbeddingInput, TextEmbeddingModel

ModuleNotFoundError: No module named 'vertexai'